DELETE localhost:8081/api/books/delete/4
Cookie:CCC312600764E6570AA14F90C1430132

###
GET localhost:8081/api/books/1

###
GET localhost:8081/api/books

###
POST localhost:8081/api/books/20
Cookie:CCC312600764E6570AA14F90C1430132
id=20;title="Астрономия";description="На протяжении всей книги читателя ждут практичные советы: из чего собрать набор юного астронома, как пользоваться такими приборами, как бинокль и телескоп, как наблюдать редкие космические явления, и многое другое!\nКартографический материал и современные иллюстрации помогут с лёгкостью находить нужные небесные тела. Словарь в конце книги поможет ребёнку запомнить разницу между звёздными, рассеянными и шаровыми скоплениями, подскажет, как простым языком объяснить сложные астрономические термины.";
price=777;publishingHouse="Эксмо";category[id]=3;dataTimeOfCreated="2023-05-05T17:08:37"

###
PUT localhost:8081/api/books/1
Cookie:CCC312600764E6570AA14F90C1430132
id=1;title="Астрономия.Тайны вселенной";description="На протяжении всей книги читателя ждут практичные советы: из чего собрать набор юного астронома, как пользоваться такими приборами, как бинокль и телескоп, как наблюдать редкие космические явления, и многое другое!\nКартографический материал и современные иллюстрации помогут с лёгкостью находить нужные небесные тела. Словарь в конце книги поможет ребёнку запомнить разницу между звёздными, рассеянными и шаровыми скоплениями, подскажет, как простым языком объяснить сложные астрономические термины.";
price=777;publishingHouse="Эксмо";category[id]=3;dataTimeOfCreated="2023-05-05T17:08:37"
